(() => {
  const SESSION_KEY = 'supply_kiosk_session_v1';
  const session = (()=>{ try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null} })();
  if(!session || !session.authToken || !session.currentPerson){ location.replace('/'); return; }
  const token = session.authToken;
  const person = session.currentPerson;
  const isManager = person.role === 'Management';
  const content = document.getElementById('content');
  const modalRoot = document.getElementById('modalRoot');
  const state = {tab:'dashboard', dashboard:null, customers:[], vehicles:[], mechanics:[], orders:[], invoices:[], suppliers:[], purchases:[], inventory:[]};
  const tabs = [
    ['dashboard','📊','Tableau de bord'],['orders','🔧','Atelier'],['calendar','📅','Planning'],['customers','👥','Clients'],
    ['vehicles','🚘','Véhicules'],['invoices','🧾','Factures'],['purchases','🚚','Achats'],['team','🧑‍🔧','Équipe']
  ];
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money = value => `${Number(value||0).toLocaleString('fr-TN',{minimumFractionDigits:3,maximumFractionDigits:3})} TND`;
  const date = value => value ? new Date(value).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'}) : '—';
  const statusClass = s => ['Payée','Livré','Reçue','Prêt'].includes(s)?'green':['Annulé','Impayée'].includes(s)?'red':['En réparation','Partielle','Commandée'].includes(s)?'orange':'blue';
  const pill = s => `<span class="pill ${statusClass(s)}">${esc(s)}</span>`;

  async function api(path, options={}){
    const res = await fetch(`/api${path}`, {method:options.method||'GET',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:options.body?JSON.stringify(options.body):undefined});
    const data = await res.json().catch(()=>({}));
    if(res.status===401){ localStorage.removeItem(SESSION_KEY); location.replace('/'); throw new Error('Session expirée'); }
    if(!res.ok || data.ok===false) throw new Error(data.detail||data.error||`Erreur HTTP ${res.status}`);
    return data;
  }
  async function loadAll(){
    const paths=['/garage/dashboard','/garage/customers','/garage/vehicles','/garage/mechanics','/garage/orders','/garage/invoices','/garage/suppliers','/garage/purchases','/inventory'];
    const [dash,customers,vehicles,mechanics,orders,invoices,suppliers,purchases,inventory] = await Promise.all(paths.map(p=>api(p)));
    Object.assign(state,{dashboard:dash,customers:customers.customers,vehicles:vehicles.vehicles,mechanics:mechanics.mechanics,orders:orders.orders,invoices:invoices.invoices,suppliers:suppliers.suppliers,purchases:purchases.purchases,inventory:inventory.inventory});
  }
  async function refresh(keys=[]){
    const map={dashboard:['/garage/dashboard','dashboard'],customers:['/garage/customers','customers'],vehicles:['/garage/vehicles','vehicles'],mechanics:['/garage/mechanics','mechanics'],orders:['/garage/orders','orders'],invoices:['/garage/invoices','invoices'],suppliers:['/garage/suppliers','suppliers'],purchases:['/garage/purchases','purchases'],inventory:['/inventory','inventory']};
    for(const key of keys){ const [path,prop]=map[key]; const data=await api(path); state[prop]=data[prop] ?? data; }
  }
  function renderNav(){
    const html=tabs.map(([id,icon,label])=>`<button class="${state.tab===id?'active':''}" data-tab="${id}">${icon} ${label}</button>`).join('');
    document.getElementById('desktopNav').innerHTML=html; document.getElementById('mobileNav').innerHTML=html;
    document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderNav();render();});
    document.getElementById('pageTitle').textContent=tabs.find(t=>t[0]===state.tab)?.[2]||'Garage Plus';
  }
  function modal(title, body, wide=false){ modalRoot.innerHTML=`<div class="modal-bg"><div class="modal ${wide?'wide':''}"><div class="modal-head"><h2>${esc(title)}</h2><button class="x" id="closeModal">×</button></div><div class="modal-body">${body}</div></div></div>`; document.getElementById('closeModal').onclick=closeModal; modalRoot.querySelector('.modal-bg').onclick=e=>{if(e.target.classList.contains('modal-bg'))closeModal()}; }
  function closeModal(){modalRoot.innerHTML=''}
  function formError(err){const el=document.getElementById('formError');if(el)el.innerHTML=`<div class="error">${esc(err.message||err)}</div>`}
  function customerOptions(selected=''){return state.customers.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.name)} · ${esc(x.phone||x.customer_code)}</option>`).join('')}
  function vehicleOptions(customerId='',selected=''){return state.vehicles.filter(x=>!customerId||x.customer_id===customerId).map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.make)} ${esc(x.model)} · ${esc(x.registration)}</option>`).join('')}
  function mechanicOptions(selected=''){return `<option value="">Non affecté</option>`+state.mechanics.filter(x=>x.is_active).map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.name)}${x.specialty?' · '+esc(x.specialty):''}</option>`).join('')}

  function render(){
    const fn={dashboard:renderDashboard,orders:renderOrders,calendar:renderCalendar,customers:renderCustomers,vehicles:renderVehicles,invoices:renderInvoices,purchases:renderPurchases,team:renderTeam}[state.tab]; fn();
  }
  function renderDashboard(){
    const d=state.dashboard||{kpis:{},orders_by_status:[],recent_orders:[]},k=d.kpis; const max=Math.max(1,...d.orders_by_status.map(x=>x.count));
    content.innerHTML=`<div class="kpis">
      ${[['Ordres actifs',k.open_orders,'Atelier en cours'],['Véhicules prêts',k.ready_orders,'À remettre aux clients'],['Chiffre facturé',money(k.revenue),'Factures émises'],['Solde à recevoir',money(k.outstanding),'Créances clients'],['Clients',k.customers,'Base clients'],['Véhicules',k.vehicles,'Parc suivi'],['Stock faible',k.low_stock,'Articles à commander']].map(x=>`<div class="kpi"><div class="label">${x[0]}</div><div class="value">${x[1]??0}</div><div class="hint">${x[2]}</div></div>`).join('')}
    </div><div class="grid2"><div class="card"><div class="card-head"><h2>Ordres récents</h2><button class="btn primary" id="quickOrder">+ Nouvel ordre</button></div><div class="card-body">${ordersTable(d.recent_orders)}</div></div><div class="card"><div class="card-head"><h2>Charge atelier</h2></div><div class="card-body status-bars">${d.orders_by_status.length?d.orders_by_status.map(x=>`<div class="status-row"><span>${esc(x.status)}</span><div class="bar"><i style="width:${x.count/max*100}%"></i></div><b>${x.count}</b></div>`).join(''):'<div class="empty">Aucun ordre</div>'}</div></div></div>`;
    document.getElementById('quickOrder').onclick=openOrderForm; bindOrderButtons();
  }
  function ordersTable(rows){return rows.length?`<table><thead><tr><th>Ordre</th><th>Client / véhicule</th><th>État</th><th>Total</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${esc(o.order_number)}</b><br><span class="muted">${date(o.opened_at)}</span></td><td>${esc(o.customer_name)}<br><span class="muted">${esc(o.vehicle)}</span></td><td>${pill(o.status)}</td><td>${money(o.total)}</td><td><button class="btn" data-open-order="${o.id}">Ouvrir</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucun ordre de réparation.</div>'}
  function bindOrderButtons(){document.querySelectorAll('[data-open-order]').forEach(b=>b.onclick=()=>openOrderDetail(b.dataset.openOrder))}
  function renderOrders(){content.innerHTML=`<div class="toolbar"><input class="search" id="orderSearch" placeholder="Rechercher ordre, client, véhicule…"><select class="btn" id="orderStatus"><option value="">Tous les états</option>${['Ouvert','Diagnostic','En attente pièces','En réparation','Prêt','Livré','Annulé'].map(x=>`<option>${x}</option>`).join('')}</select><button class="btn primary" id="addOrder">+ Nouvel ordre</button></div><div id="ordersArea">${ordersTable(state.orders)}</div>`; document.getElementById('addOrder').onclick=openOrderForm; const filter=()=>{const q=document.getElementById('orderSearch').value.toLowerCase(),s=document.getElementById('orderStatus').value;const rows=state.orders.filter(o=>(!s||o.status===s)&&(!q||JSON.stringify(o).toLowerCase().includes(q)));document.getElementById('ordersArea').innerHTML=ordersTable(rows);bindOrderButtons()};document.getElementById('orderSearch').oninput=filter;document.getElementById('orderStatus').onchange=filter;bindOrderButtons()}
  function renderCalendar(){const scheduled=state.orders.filter(x=>x.scheduled_for&& !['Livré','Annulé'].includes(x.status)).sort((a,b)=>new Date(a.scheduled_for)-new Date(b.scheduled_for));const groups={};scheduled.forEach(x=>{const key=new Date(x.scheduled_for).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});(groups[key]??=[]).push(x)});content.innerHTML=`<div class="toolbar"><div class="muted">Rendez-vous et travaux planifiés</div><button class="btn primary" id="calendarAdd">+ Rendez-vous atelier</button></div>${Object.keys(groups).length?Object.entries(groups).map(([day,rows])=>`<div class="card" style="margin-bottom:14px"><div class="card-head"><h2>${esc(day)}</h2><span class="pill blue">${rows.length}</span></div><div class="card-body">${rows.map(o=>`<div style="display:grid;grid-template-columns:75px 1fr auto;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line)"><b>${new Date(o.scheduled_for).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</b><div><b>${esc(o.vehicle)}</b><br><span class="muted">${esc(o.customer_name)} · ${esc(o.complaint)}</span></div><button class="btn" data-open-order="${o.id}">Ouvrir</button></div>`).join('')}</div></div>`).join(''):'<div class="empty">Aucun rendez-vous planifié.</div>'}`;document.getElementById('calendarAdd').onclick=openOrderForm;bindOrderButtons()}
  function renderCustomers(){content.innerHTML=`<div class="toolbar"><input class="search" id="customerSearch" placeholder="Rechercher client, téléphone ou code…"><button class="btn primary" id="addCustomer">+ Nouveau client</button></div><div id="customersArea">${customersTable(state.customers)}</div>`;document.getElementById('addCustomer').onclick=openCustomerForm;document.getElementById('customerSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('customersArea').innerHTML=customersTable(state.customers.filter(x=>JSON.stringify(x).toLowerCase().includes(q)))} }
  function customersTable(rows){return rows.length?`<table><thead><tr><th>Code</th><th>Client</th><th>Contact</th><th>Adresse</th><th>Créé</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.customer_code)}</td><td><b>${esc(x.name)}</b><br><span class="muted">${esc(x.tax_id||'')}</span></td><td>${esc(x.phone||'—')}<br><span class="muted">${esc(x.email||'')}</span></td><td>${esc(x.address||'—')}</td><td>${date(x.created_at)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucun client enregistré.</div>'}
  function renderVehicles(){content.innerHTML=`<div class="toolbar"><input class="search" id="vehicleSearch" placeholder="Immatriculation, VIN, modèle…"><button class="btn primary" id="addVehicle">+ Nouveau véhicule</button></div><div id="vehiclesArea">${vehiclesTable(state.vehicles)}</div>`;document.getElementById('addVehicle').onclick=openVehicleForm;document.getElementById('vehicleSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('vehiclesArea').innerHTML=vehiclesTable(state.vehicles.filter(x=>JSON.stringify(x).toLowerCase().includes(q)));bindVehicleHistory()};bindVehicleHistory()}
  function vehiclesTable(rows){return rows.length?`<table><thead><tr><th>Immatriculation</th><th>Véhicule</th><th>Client</th><th>VIN</th><th>Kilométrage</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.registration)}</b></td><td>${esc(x.make)} ${esc(x.model)} ${x.year?'('+x.year+')':''}<br><span class="muted">${esc(x.color||'')}</span></td><td>${esc(x.customer_name)}</td><td>${esc(x.vin||'—')}</td><td>${x.mileage!=null?Number(x.mileage).toLocaleString('fr-FR')+' km':'—'}</td><td><button class="btn" data-vehicle-history="${x.id}">Historique</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucun véhicule enregistré.</div>'}
  function bindVehicleHistory(){document.querySelectorAll('[data-vehicle-history]').forEach(b=>b.onclick=()=>openVehicleHistory(b.dataset.vehicleHistory))}
  async function openVehicleHistory(id){try{const out=await api(`/garage/vehicles/${id}/history`);const v=out.vehicle;modal(`Historique · ${v.registration}`,`<div class="detail-head"><div><h3>${esc(v.make)} ${esc(v.model)}</h3><span class="muted">${esc(v.customer_name)} · VIN ${esc(v.vin||'non renseigné')} · ${v.mileage!=null?Number(v.mileage).toLocaleString('fr-FR')+' km':'kilométrage non renseigné'}</span></div></div>${ordersTable(out.orders)}`,true);bindOrderButtons()}catch(err){alert(err.message)}}
  function renderInvoices(){content.innerHTML=`<div class="toolbar"><div class="muted">Les factures sont générées depuis un ordre de réparation.</div></div>${state.invoices.length?`<table><thead><tr><th>Facture</th><th>Client / ordre</th><th>État</th><th>Total</th><th>Payé</th><th>Solde</th><th></th></tr></thead><tbody>${state.invoices.map(x=>`<tr><td><b>${esc(x.invoice_number)}</b><br><span class="muted">${date(x.issued_at)}</span></td><td>${esc(x.customer_name)}<br><span class="muted">${esc(x.order_number)}</span></td><td>${pill(x.status)}</td><td>${money(x.total)}</td><td>${money(x.paid_amount)}</td><td>${money(x.balance)}</td><td><button class="btn" data-print="${x.id}">Imprimer</button> ${isManager&&x.balance>0?`<button class="btn" data-pay="${x.id}">Règlement</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucune facture.</div>'}`;document.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>openPaymentForm(b.dataset.pay));document.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>window.open(`/garage-invoice.html?id=${encodeURIComponent(b.dataset.print)}`,'_blank'))}
  function renderPurchases(){content.innerHTML=`<div class="toolbar"><button class="btn" id="suppliersBtn">Fournisseurs (${state.suppliers.length})</button>${isManager?'<button class="btn primary" id="addPurchase">+ Commande fournisseur</button>':''}</div>${state.purchases.length?`<table><thead><tr><th>Commande</th><th>Fournisseur</th><th>État</th><th>Total</th><th>Prévue</th><th></th></tr></thead><tbody>${state.purchases.map(x=>`<tr><td><b>${esc(x.purchase_number)}</b><br><span class="muted">${date(x.ordered_at)}</span></td><td>${esc(x.supplier_name)}</td><td>${pill(x.status)}</td><td>${money(x.total)}</td><td>${date(x.expected_at)}</td><td>${isManager&&!['Reçue'].includes(x.status)?`<button class="btn" data-receive="${x.id}">Réceptionner</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucune commande fournisseur.</div>'}`;document.getElementById('suppliersBtn').onclick=openSuppliers;if(isManager)document.getElementById('addPurchase').onclick=openPurchaseForm;document.querySelectorAll('[data-receive]').forEach(b=>b.onclick=()=>receivePurchase(b.dataset.receive))}
  function renderTeam(){content.innerHTML=`<div class="toolbar">${isManager?'<button class="btn primary" id="addMechanic">+ Mécanicien</button>':''}</div>${state.mechanics.length?`<table><thead><tr><th>Nom</th><th>Spécialité</th><th>Téléphone</th><th>Taux horaire</th><th>État</th></tr></thead><tbody>${state.mechanics.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.specialty||'—')}</td><td>${esc(x.phone||'—')}</td><td>${money(x.hourly_rate)}</td><td>${x.is_active?pill('Actif'):pill('Inactif')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucun mécanicien enregistré.</div>'}`;if(isManager)document.getElementById('addMechanic').onclick=openMechanicForm}

  function openCustomerForm(){modal('Nouveau client',`<div id="formError"></div><form id="entityForm"><div class="form-grid"><div class="field full"><label>Nom / raison sociale *</label><input name="name" required></div><div class="field"><label>Téléphone</label><input name="phone"></div><div class="field"><label>E-mail</label><input name="email" type="email"></div><div class="field"><label>Matricule fiscal</label><input name="tax_id"></div><div class="field full"><label>Adresse</label><textarea name="address"></textarea></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Enregistrer</button></div></form>`);bindBasicForm('/garage/customers',['customers','dashboard'])}
  function openVehicleForm(){if(!state.customers.length){alert('Créez d’abord un client.');return}modal('Nouveau véhicule',`<div id="formError"></div><form id="entityForm"><div class="form-grid"><div class="field full"><label>Client *</label><select name="customer_id" required>${customerOptions()}</select></div><div class="field"><label>Immatriculation *</label><input name="registration" required></div><div class="field"><label>VIN</label><input name="vin"></div><div class="field"><label>Marque *</label><input name="make" value="KIA" required></div><div class="field"><label>Modèle *</label><input name="model" required></div><div class="field"><label>Année</label><input name="year" type="number"></div><div class="field"><label>Kilométrage</label><input name="mileage" type="number"></div><div class="field"><label>Couleur</label><input name="color"></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Enregistrer</button></div></form>`);bindBasicForm('/garage/vehicles',['vehicles','dashboard'],['year','mileage'])}
  function openMechanicForm(){modal('Nouveau mécanicien',`<div id="formError"></div><form id="entityForm"><div class="form-grid"><div class="field full"><label>Nom *</label><input name="name" required></div><div class="field"><label>Spécialité</label><input name="specialty"></div><div class="field"><label>Téléphone</label><input name="phone"></div><div class="field"><label>Taux horaire (TND)</label><input name="hourly_rate" type="number" min="0" step="0.001" value="0"></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Enregistrer</button></div></form>`);bindBasicForm('/garage/mechanics',['mechanics'],['hourly_rate'])}
  function bindBasicForm(path,refreshKeys,numbers=[]){document.getElementById('cancel').onclick=closeModal;document.getElementById('entityForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));for(const key of numbers)body[key]=body[key]?Number(body[key]):null;Object.keys(body).forEach(k=>{if(body[k]==='')body[k]=null});try{await api(path,{method:'POST',body});await refresh(refreshKeys);closeModal();render()}catch(err){formError(err)}}}
  function openOrderForm(){if(!state.customers.length||!state.vehicles.length){alert('Créez d’abord un client et son véhicule.');return}modal('Nouvel ordre de réparation',`<div id="formError"></div><form id="orderForm"><div class="form-grid"><div class="field"><label>Client *</label><select id="orderCustomer" name="customer_id" required>${customerOptions()}</select></div><div class="field"><label>Véhicule *</label><select id="orderVehicle" name="vehicle_id" required></select></div><div class="field"><label>Mécanicien</label><select name="mechanic_id">${mechanicOptions()}</select></div><div class="field"><label>Priorité</label><select name="priority"><option>Normale</option><option>Basse</option><option>Haute</option><option>Urgente</option></select></div><div class="field"><label>Kilométrage d’entrée</label><input name="mileage_in" type="number" min="0"></div><div class="field"><label>Rendez-vous</label><input name="scheduled_for" type="datetime-local"></div><div class="field full"><label>Demande / panne signalée *</label><textarea name="complaint" required></textarea></div><div class="field full"><label>Notes internes</label><textarea name="internal_notes"></textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Créer l’ordre</button></div></form>`);const c=document.getElementById('orderCustomer'),v=document.getElementById('orderVehicle');const sync=()=>v.innerHTML=vehicleOptions(c.value);c.onchange=sync;sync();document.getElementById('cancel').onclick=closeModal;document.getElementById('orderForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.mileage_in=body.mileage_in?Number(body.mileage_in):null;for(const k of ['mechanic_id','scheduled_for','internal_notes'])if(!body[k])body[k]=null;try{const out=await api('/garage/orders',{method:'POST',body});await refresh(['orders','dashboard']);closeModal();render();openOrderDetail(out.order.id)}catch(err){formError(err)}}}
  function openOrderDetail(id){const o=state.orders.find(x=>x.id===id)||state.dashboard?.recent_orders.find(x=>x.id===id);if(!o)return;const options=['Ouvert','Diagnostic','En attente pièces','En réparation','Prêt','Livré','Annulé'].map(x=>`<option ${o.status===x?'selected':''}>${x}</option>`).join('');modal(`Ordre ${o.order_number}`,`<div id="formError"></div><div class="detail-head"><div><h3>${esc(o.customer_name)}</h3><span class="muted">${esc(o.vehicle)} · ${date(o.opened_at)}</span><p>${esc(o.complaint)}</p></div><div><select class="btn" id="detailStatus">${options}</select></div></div><div class="form-grid"><div class="field"><label>Mécanicien</label><select id="detailMechanic">${mechanicOptions(o.mechanic_id)}</select></div><div class="field"><label>Diagnostic</label><textarea id="detailDiagnosis">${esc(o.diagnosis||'')}</textarea></div></div><div class="form-actions"><button class="btn" id="saveOrder">Mettre à jour</button></div><div class="card" style="margin-top:18px"><div class="card-head"><h2>Main-d’œuvre, services et pièces</h2><button class="btn primary" id="addLine">+ Ligne</button></div><div class="card-body">${o.lines?.length?`<table><thead><tr><th>Type</th><th>Description</th><th>Qté</th><th>Prix</th><th>Total</th></tr></thead><tbody>${o.lines.map(l=>`<tr><td>${esc(l.line_type)}</td><td>${esc(l.description)}</td><td>${l.quantity}</td><td>${money(l.unit_price)}</td><td>${money(l.total)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucune ligne.</div>'}<div class="totals" style="margin-top:16px"><div class="grand"><span>Total HT</span><span>${money(o.total)}</span></div></div></div></div>${isManager?`<div class="form-actions"><button class="btn primary" id="invoiceOrder" ${!o.lines?.length?'disabled':''}>Générer la facture</button></div>`:''}`,true);document.getElementById('saveOrder').onclick=async()=>{try{await api(`/garage/orders/${o.id}`,{method:'PATCH',body:{status:document.getElementById('detailStatus').value,mechanic_id:document.getElementById('detailMechanic').value||null,diagnosis:document.getElementById('detailDiagnosis').value||null}});await refresh(['orders','dashboard']);closeModal();render()}catch(err){formError(err)}};document.getElementById('addLine').onclick=()=>openLineForm(o.id);if(isManager)document.getElementById('invoiceOrder').onclick=()=>createInvoice(o.id)}
  function openLineForm(orderId){const partOptions=state.inventory.filter(x=>x.reference==='Station Parts').map(x=>`<option value="${esc(x.item)}">${esc(x.item)} · stock ${x.quantity} · ${esc(x.serial_number||'sans série')}</option>`).join('');modal('Ajouter une ligne',`<div id="formError"></div><form id="lineForm"><div class="form-grid"><div class="field"><label>Type</label><select name="line_type" id="lineType"><option value="labor">Main-d’œuvre</option><option value="service">Service</option><option value="part">Pièce</option></select></div><div class="field"><label>Pièce de stock</label><select id="stockPart"><option value="">Aucune</option>${partOptions}</select></div><div class="field full"><label>Description *</label><input name="description" id="lineDescription" required></div><div class="field"><label>Quantité / heures</label><input name="quantity" type="number" min="0.001" step="0.001" value="1"></div><div class="field"><label>Prix unitaire</label><input name="unit_price" type="number" min="0" step="0.001" value="0"></div><div class="field"><label>Coût unitaire</label><input name="unit_cost" type="number" min="0" step="0.001" value="0"></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Ajouter</button></div></form>`);document.getElementById('cancel').onclick=closeModal;document.getElementById('stockPart').onchange=e=>{const item=state.inventory.find(x=>x.item===e.target.value);if(item){document.getElementById('lineType').value='part';document.getElementById('lineDescription').value=item.item}};document.getElementById('lineForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));const selected=state.inventory.find(x=>x.item===document.getElementById('stockPart').value);body.inventory_item_id=selected?selected.id:null;body.quantity=Number(body.quantity);body.unit_price=Number(body.unit_price);body.unit_cost=Number(body.unit_cost);try{const out=await api(`/garage/orders/${orderId}/lines`,{method:'POST',body});await refresh(['orders','dashboard','inventory']);closeModal();render();state.orders=state.orders.map(x=>x.id===orderId?out.order:x);openOrderDetail(orderId)}catch(err){formError(err)}}}
  async function createInvoice(orderId){try{await api('/garage/invoices',{method:'POST',body:{repair_order_id:orderId,tax_rate:19,discount:0}});await refresh(['invoices','dashboard']);closeModal();state.tab='invoices';renderNav();render()}catch(err){formError(err)}}
  function openPaymentForm(id){const inv=state.invoices.find(x=>x.id===id);modal(`Règlement ${inv.invoice_number}`,`<div id="formError"></div><form id="paymentForm"><div class="kpi"><div class="label">Solde</div><div class="value">${money(inv.balance)}</div></div><div class="form-grid" style="margin-top:16px"><div class="field"><label>Montant *</label><input name="amount" type="number" min="0.001" max="${inv.balance}" step="0.001" value="${inv.balance}" required></div><div class="field"><label>Mode</label><select name="method"><option>Espèces</option><option>Carte</option><option>Virement</option><option>Chèque</option><option>Autre</option></select></div><div class="field full"><label>Référence</label><input name="reference"></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Valider</button></div></form>`);document.getElementById('cancel').onclick=closeModal;document.getElementById('paymentForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.amount=Number(body.amount);if(!body.reference)body.reference=null;try{await api(`/garage/invoices/${id}/payments`,{method:'POST',body});await refresh(['invoices','dashboard']);closeModal();render()}catch(err){formError(err)}}}
  function openSuppliers(){modal('Fournisseurs',`${isManager?'<button class="btn primary" id="addSupplier">+ Fournisseur</button>':''}<div style="margin-top:14px">${state.suppliers.length?`<table><thead><tr><th>Code</th><th>Nom</th><th>Contact</th></tr></thead><tbody>${state.suppliers.map(x=>`<tr><td>${esc(x.supplier_code)}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.phone||'—')}<br><span class="muted">${esc(x.email||'')}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Aucun fournisseur.</div>'}</div>`);if(isManager)document.getElementById('addSupplier').onclick=openSupplierForm}
  function openSupplierForm(){modal('Nouveau fournisseur',`<div id="formError"></div><form id="entityForm"><div class="form-grid"><div class="field full"><label>Nom *</label><input name="name" required></div><div class="field"><label>Contact</label><input name="contact_name"></div><div class="field"><label>Téléphone</label><input name="phone"></div><div class="field"><label>E-mail</label><input name="email" type="email"></div><div class="field"><label>Matricule fiscal</label><input name="tax_id"></div><div class="field full"><label>Adresse</label><textarea name="address"></textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Enregistrer</button></div></form>`);bindBasicForm('/garage/suppliers',['suppliers'])}
  function openPurchaseForm(){if(!state.suppliers.length){openSupplierForm();return}const stock=state.inventory.filter(x=>x.reference==='Station Parts');modal('Commande fournisseur',`<div id="formError"></div><form id="purchaseForm"><div class="form-grid"><div class="field"><label>Fournisseur *</label><select name="supplier_id">${state.suppliers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Réception prévue</label><input name="expected_at" type="datetime-local"></div><div class="field full"><label>Article de stock *</label><select name="inventory_item_name">${stock.map(x=>`<option value="${esc(x.item)}">${esc(x.item)} · stock ${x.quantity}</option>`).join('')}</select></div><div class="field"><label>Quantité *</label><input name="quantity" type="number" min="1" value="1"></div><div class="field"><label>Coût unitaire</label><input name="unit_cost" type="number" min="0" step="0.001" value="0"></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancel">Annuler</button><button class="btn primary">Commander</button></div></form>`);document.getElementById('cancel').onclick=closeModal;document.getElementById('purchaseForm').onsubmit=async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.target));const item=state.inventory.find(x=>x.item===raw.inventory_item_name);const body={supplier_id:raw.supplier_id,expected_at:raw.expected_at||null,notes:raw.notes||null,lines:[{inventory_item_id:item?.id||null,description:raw.inventory_item_name,quantity:Number(raw.quantity),unit_cost:Number(raw.unit_cost)}]};try{await api('/garage/purchases',{method:'POST',body});await refresh(['purchases','dashboard']);closeModal();render()}catch(err){formError(err)}}}
  async function receivePurchase(id){if(!confirm('Confirmer la réception des quantités restantes ?'))return;try{await api(`/garage/purchases/${id}/receive`,{method:'POST',body:{received_quantities:null}});await refresh(['purchases','dashboard','inventory']);render()}catch(err){alert(err.message)}}

  document.getElementById('personName').textContent=person.name;document.getElementById('personRole').textContent=person.role;
  document.getElementById('backStock').onclick=()=>location.href='/';document.getElementById('logout').onclick=()=>{localStorage.removeItem(SESSION_KEY);location.replace('/')};
  ['click','keydown','touchstart'].forEach(evt=>document.addEventListener(evt,()=>{session.lastActivity=Date.now();localStorage.setItem(SESSION_KEY,JSON.stringify(session))},{passive:true}));
  renderNav();loadAll().then(render).catch(err=>{content.innerHTML=`<div class="error">${esc(err.message)}</div>`});
})();
